### ISSUE TITLE
Error after upgrade in 1.4.0 for Windows

### ISSUE THREAD

**Issue by Ngapi** [felixbrucker/chia-dashboard-satellite#21]
**Describe the bug**
I start the application and it offers the API key but then I get an error in the node

**To Reproduce**
Click on chia-dashboard-satellite.exe
And Error after insert api key

**Screenshots**

![2021-05-11_22h31_37](https://user-images.githubusercontent.com/16021205/117880911-eb7cb300-b2a8-11eb-956f-3a42c6cc4d0e.png)

**System (please complete the following information):**
 - OS : Windows 10 Pro 
 - NodeJs Version : 14.16.1

**Comment by Ngapi** [comment]
If I understand correctly it happens during CPU overload due to parallel plot plotting, is there a solution to allow caching of data to avoid node errors?

**Comment by kalosbg** [comment]
Are you sure that the issue is caused by CPU overload because in my case I have CPU resources:
![image](https://user-images.githubusercontent.com/22997358/117931438-da16c380-b307-11eb-99ab-e6b105929a23.png)
Is it possible timeout handler to be implemented that will retry from time to time?

**Comment by felixbrucker** [comment]
The problem is not cpu bound, rather there is a bug osmewhere in chia-blockchain or the gui that causes the daemon/services to not respond to simple api requests in a timely fashion, or at all.

That being said i'll have a look at improving the initial stat retrieval so that it will try again till the chia node is working correctly again.

**Comment by felixbrucker** [comment]
With v1.5.0 the initialization now catches errors such as slow/unresponsive chia nodes and retries the api requests till the chia node is responding again.
